client:
  car:
    basic:
      base-url: https://easy-mock.com/mock/5b2a3e2aac9572284a2f11c9
      headers:
        TOKEN: 1234567890
        SIGN: 1234567890
        Accept: application/json
      query-url: /cm/cars/{id}
      query-page-url: /cars?page={page}&size={page}
    manage:
      base-url: https://easy-mock.com/mock/5b2a3e2aac9572284a2f11c9
