server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    accesslog:
      enabled: true
app:
  base-package: com.my.sample.core
spring:
  application:
    name: sample-core
  profiles:
    include:
    - datasource
    - client
  pid:
    file: ${spring.application.name}.pid
    fail-on-write-error: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
    favicon:
      enabled: true
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    converters:
      preferred-json-mapper: jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  data:
    web:
      pageable:
        one-indexed-parameters: true # 默认第一页页码为1，不要与spring-boot-starter-data-rest一起用，否则会失效
        default-page-size: 10 # 默认分页大小

logging:
  config: ${spring.config.location:classpath:config}/logback.xml
#swagger config
swagger:
  title: 代码示例
  description: 地网-代码示例
  version: 0.0.1
  contact:
    name: shiyongbiao
  base-package: ${app.base-package}
  enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - health
        - info
        - configprops
        - mappings
        - scheduledtasks
        - beans